# Generated by Django 4.1.2 on 2022-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(through='Inventory.ProductQuantity', to='Inventory.product'),
        ),
    ]
