# Generated by Django 4.0.2 on 2022-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[(1, 'piece'), (2, 'liter'), (3, 'kilogram')], max_length=1),
        ),
    ]
