# Generated by Django 4.1.2 on 2022-10-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_inventory_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product'),
        ),
    ]
