# Generated by Django 4.1.2 on 2022-10-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='amount',
            field=models.FloatField(),
        ),
    ]
