# Generated by Django 4.1.2 on 2022-11-01 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_inventory_amount_alter_productquantity_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0)]),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 0)]),
        ),
    ]
